---
app:
  jwt:
    base64-secret: "${APP_JWT_BASE64_SECRET:}"
    access-token-validity: "86400"    # 1 day in seconds
    refresh-token-validity: "3888000" # 45 days in seconds
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "${SPRING_DATASOURCE_URL}"
    username: "${SPRING_DATASOURCE_USERNAME}"
    password: "${SPRING_DATASOURCE_PASSWORD}"
server:
  port: "${PORT:8080}"

---
spring:
  profiles: local
  datasource:
    url: "jdbc:postgresql://localhost:5432/auth-backend"
    username: "auth"
    password: "auth"
  jpa:
    show-sql: "true"
